### ISSUE TITLE
Serialization and Deserialization of NIZKs

### ISSUE THREAD

**Issue by ravirahman** [spring-epfl/zksk#4]
I am working on a project where I need to share NIZKs between two systems. Does the library support serialization and desterilization of `zksk.base.NZIK`? For security reasons, I would like to avoid using Python's `pickle`.

Thanks!

**Comment by laurent-girod** [comment]
Thank you for your request.

We added two serialization methods to the `NIZK` class. A NIZK object can now be serialized/deserialized as such:
```python
from zksk.base import NIZK

nizk_enc = nizk.serialize()
nizk_dec = NIZK.deserialize(nizk_enc)
```

I hope these changes will be useful.

**Comment by ravirahman** [comment]
Thank you for adding in this feature!

**Comment by laurent-girod** [comment]
You're welcome!
